package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShipmentMiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentMiAllPropertiesEquals(ShipmentMi expected, ShipmentMi actual) {
        assertShipmentMiAutoGeneratedPropertiesEquals(expected, actual);
        assertShipmentMiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentMiAllUpdatablePropertiesEquals(ShipmentMi expected, ShipmentMi actual) {
        assertShipmentMiUpdatableFieldsEquals(expected, actual);
        assertShipmentMiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentMiAutoGeneratedPropertiesEquals(ShipmentMi expected, ShipmentMi actual) {
        assertThat(expected)
            .as("Verify ShipmentMi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentMiUpdatableFieldsEquals(ShipmentMi expected, ShipmentMi actual) {
        assertThat(expected)
            .as("Verify ShipmentMi relevant properties")
            .satisfies(e -> assertThat(e.getTrackingNumber()).as("check trackingNumber").isEqualTo(actual.getTrackingNumber()))
            .satisfies(e -> assertThat(e.getShippedDate()).as("check shippedDate").isEqualTo(actual.getShippedDate()))
            .satisfies(e -> assertThat(e.getDeliveryDate()).as("check deliveryDate").isEqualTo(actual.getDeliveryDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentMiUpdatableRelationshipsEquals(ShipmentMi expected, ShipmentMi actual) {
        // empty method
    }
}
