package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SupplierViViAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplierViViAllPropertiesEquals(SupplierViVi expected, SupplierViVi actual) {
        assertSupplierViViAutoGeneratedPropertiesEquals(expected, actual);
        assertSupplierViViAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplierViViAllUpdatablePropertiesEquals(SupplierViVi expected, SupplierViVi actual) {
        assertSupplierViViUpdatableFieldsEquals(expected, actual);
        assertSupplierViViUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplierViViAutoGeneratedPropertiesEquals(SupplierViVi expected, SupplierViVi actual) {
        assertThat(expected)
            .as("Verify SupplierViVi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplierViViUpdatableFieldsEquals(SupplierViVi expected, SupplierViVi actual) {
        assertThat(expected)
            .as("Verify SupplierViVi relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getContactPerson()).as("check contactPerson").isEqualTo(actual.getContactPerson()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getPhoneNumber()).as("check phoneNumber").isEqualTo(actual.getPhoneNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplierViViUpdatableRelationshipsEquals(SupplierViVi expected, SupplierViVi actual) {
        assertThat(expected)
            .as("Verify SupplierViVi relationships")
            .satisfies(e -> assertThat(e.getProducts()).as("check products").isEqualTo(actual.getProducts()));
    }
}
