package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SupplierViAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplierViAllPropertiesEquals(SupplierVi expected, SupplierVi actual) {
        assertSupplierViAutoGeneratedPropertiesEquals(expected, actual);
        assertSupplierViAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplierViAllUpdatablePropertiesEquals(SupplierVi expected, SupplierVi actual) {
        assertSupplierViUpdatableFieldsEquals(expected, actual);
        assertSupplierViUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplierViAutoGeneratedPropertiesEquals(SupplierVi expected, SupplierVi actual) {
        assertThat(expected)
            .as("Verify SupplierVi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplierViUpdatableFieldsEquals(SupplierVi expected, SupplierVi actual) {
        assertThat(expected)
            .as("Verify SupplierVi relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getContactPerson()).as("check contactPerson").isEqualTo(actual.getContactPerson()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getPhoneNumber()).as("check phoneNumber").isEqualTo(actual.getPhoneNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplierViUpdatableRelationshipsEquals(SupplierVi expected, SupplierVi actual) {
        assertThat(expected)
            .as("Verify SupplierVi relationships")
            .satisfies(e -> assertThat(e.getProducts()).as("check products").isEqualTo(actual.getProducts()));
    }
}
