package ai.realworld.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlAppleViAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlAppleViAllPropertiesEquals(AlAppleVi expected, AlAppleVi actual) {
        assertAlAppleViAutoGeneratedPropertiesEquals(expected, actual);
        assertAlAppleViAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlAppleViAllUpdatablePropertiesEquals(AlAppleVi expected, AlAppleVi actual) {
        assertAlAppleViUpdatableFieldsEquals(expected, actual);
        assertAlAppleViUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlAppleViAutoGeneratedPropertiesEquals(AlAppleVi expected, AlAppleVi actual) {
        assertThat(expected)
            .as("Verify AlAppleVi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlAppleViUpdatableFieldsEquals(AlAppleVi expected, AlAppleVi actual) {
        assertThat(expected)
            .as("Verify AlAppleVi relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getHotline()).as("check hotline").isEqualTo(actual.getHotline()))
            .satisfies(e -> assertThat(e.getTaxCode()).as("check taxCode").isEqualTo(actual.getTaxCode()))
            .satisfies(e -> assertThat(e.getContactsJason()).as("check contactsJason").isEqualTo(actual.getContactsJason()))
            .satisfies(e -> assertThat(e.getExtensionJason()).as("check extensionJason").isEqualTo(actual.getExtensionJason()))
            .satisfies(e -> assertThat(e.getIsEnabled()).as("check isEnabled").isEqualTo(actual.getIsEnabled()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlAppleViUpdatableRelationshipsEquals(AlAppleVi expected, AlAppleVi actual) {
        assertThat(expected)
            .as("Verify AlAppleVi relationships")
            .satisfies(e -> assertThat(e.getAddress()).as("check address").isEqualTo(actual.getAddress()))
            .satisfies(e -> assertThat(e.getAgencyType()).as("check agencyType").isEqualTo(actual.getAgencyType()))
            .satisfies(e -> assertThat(e.getLogo()).as("check logo").isEqualTo(actual.getLogo()))
            .satisfies(e -> assertThat(e.getApplication()).as("check application").isEqualTo(actual.getApplication()));
    }
}
