package ai.realworld.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlPowerShellViAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlPowerShellViAllPropertiesEquals(AlPowerShellVi expected, AlPowerShellVi actual) {
        assertAlPowerShellViAutoGeneratedPropertiesEquals(expected, actual);
        assertAlPowerShellViAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlPowerShellViAllUpdatablePropertiesEquals(AlPowerShellVi expected, AlPowerShellVi actual) {
        assertAlPowerShellViUpdatableFieldsEquals(expected, actual);
        assertAlPowerShellViUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlPowerShellViAutoGeneratedPropertiesEquals(AlPowerShellVi expected, AlPowerShellVi actual) {
        assertThat(expected)
            .as("Verify AlPowerShellVi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlPowerShellViUpdatableFieldsEquals(AlPowerShellVi expected, AlPowerShellVi actual) {
        assertThat(expected)
            .as("Verify AlPowerShellVi relevant properties")
            .satisfies(e -> assertThat(e.getValue()).as("check value").isEqualTo(actual.getValue()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlPowerShellViUpdatableRelationshipsEquals(AlPowerShellVi expected, AlPowerShellVi actual) {
        assertThat(expected)
            .as("Verify AlPowerShellVi relationships")
            .satisfies(e -> assertThat(e.getPropertyProfile()).as("check propertyProfile").isEqualTo(actual.getPropertyProfile()))
            .satisfies(e -> assertThat(e.getAttributeTerm()).as("check attributeTerm").isEqualTo(actual.getAttributeTerm()))
            .satisfies(e -> assertThat(e.getApplication()).as("check application").isEqualTo(actual.getApplication()));
    }
}
