package ai.realworld.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlSherMaleViAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlSherMaleViAllPropertiesEquals(AlSherMaleVi expected, AlSherMaleVi actual) {
        assertAlSherMaleViAutoGeneratedPropertiesEquals(expected, actual);
        assertAlSherMaleViAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlSherMaleViAllUpdatablePropertiesEquals(AlSherMaleVi expected, AlSherMaleVi actual) {
        assertAlSherMaleViUpdatableFieldsEquals(expected, actual);
        assertAlSherMaleViUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlSherMaleViAutoGeneratedPropertiesEquals(AlSherMaleVi expected, AlSherMaleVi actual) {
        assertThat(expected)
            .as("Verify AlSherMaleVi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlSherMaleViUpdatableFieldsEquals(AlSherMaleVi expected, AlSherMaleVi actual) {
        assertThat(expected)
            .as("Verify AlSherMaleVi relevant properties")
            .satisfies(e ->
                assertThat(e.getDataSourceMappingType()).as("check dataSourceMappingType").isEqualTo(actual.getDataSourceMappingType())
            )
            .satisfies(e -> assertThat(e.getKeyword()).as("check keyword").isEqualTo(actual.getKeyword()))
            .satisfies(e -> assertThat(e.getProperty()).as("check property").isEqualTo(actual.getProperty()))
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlSherMaleViUpdatableRelationshipsEquals(AlSherMaleVi expected, AlSherMaleVi actual) {
        assertThat(expected)
            .as("Verify AlSherMaleVi relationships")
            .satisfies(e -> assertThat(e.getApplication()).as("check application").isEqualTo(actual.getApplication()));
    }
}
