package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CustomerMiMiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerMiMiAllPropertiesEquals(CustomerMiMi expected, CustomerMiMi actual) {
        assertCustomerMiMiAutoGeneratedPropertiesEquals(expected, actual);
        assertCustomerMiMiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerMiMiAllUpdatablePropertiesEquals(CustomerMiMi expected, CustomerMiMi actual) {
        assertCustomerMiMiUpdatableFieldsEquals(expected, actual);
        assertCustomerMiMiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerMiMiAutoGeneratedPropertiesEquals(CustomerMiMi expected, CustomerMiMi actual) {
        assertThat(expected)
            .as("Verify CustomerMiMi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerMiMiUpdatableFieldsEquals(CustomerMiMi expected, CustomerMiMi actual) {
        assertThat(expected)
            .as("Verify CustomerMiMi relevant properties")
            .satisfies(e -> assertThat(e.getFirstName()).as("check firstName").isEqualTo(actual.getFirstName()))
            .satisfies(e -> assertThat(e.getLastName()).as("check lastName").isEqualTo(actual.getLastName()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getPhoneNumber()).as("check phoneNumber").isEqualTo(actual.getPhoneNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerMiMiUpdatableRelationshipsEquals(CustomerMiMi expected, CustomerMiMi actual) {
        assertThat(expected)
            .as("Verify CustomerMiMi relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
