package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CategoryGammaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoryGammaAllPropertiesEquals(CategoryGamma expected, CategoryGamma actual) {
        assertCategoryGammaAutoGeneratedPropertiesEquals(expected, actual);
        assertCategoryGammaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoryGammaAllUpdatablePropertiesEquals(CategoryGamma expected, CategoryGamma actual) {
        assertCategoryGammaUpdatableFieldsEquals(expected, actual);
        assertCategoryGammaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoryGammaAutoGeneratedPropertiesEquals(CategoryGamma expected, CategoryGamma actual) {
        assertThat(expected)
            .as("Verify CategoryGamma auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoryGammaUpdatableFieldsEquals(CategoryGamma expected, CategoryGamma actual) {
        assertThat(expected)
            .as("Verify CategoryGamma relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoryGammaUpdatableRelationshipsEquals(CategoryGamma expected, CategoryGamma actual) {
        assertThat(expected)
            .as("Verify CategoryGamma relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
