package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EmployeeAlphaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmployeeAlphaAllPropertiesEquals(EmployeeAlpha expected, EmployeeAlpha actual) {
        assertEmployeeAlphaAutoGeneratedPropertiesEquals(expected, actual);
        assertEmployeeAlphaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmployeeAlphaAllUpdatablePropertiesEquals(EmployeeAlpha expected, EmployeeAlpha actual) {
        assertEmployeeAlphaUpdatableFieldsEquals(expected, actual);
        assertEmployeeAlphaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmployeeAlphaAutoGeneratedPropertiesEquals(EmployeeAlpha expected, EmployeeAlpha actual) {
        assertThat(expected)
            .as("Verify EmployeeAlpha auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmployeeAlphaUpdatableFieldsEquals(EmployeeAlpha expected, EmployeeAlpha actual) {
        assertThat(expected)
            .as("Verify EmployeeAlpha relevant properties")
            .satisfies(e -> assertThat(e.getFirstName()).as("check firstName").isEqualTo(actual.getFirstName()))
            .satisfies(e -> assertThat(e.getLastName()).as("check lastName").isEqualTo(actual.getLastName()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getHireDate()).as("check hireDate").isEqualTo(actual.getHireDate()))
            .satisfies(e -> assertThat(e.getPosition()).as("check position").isEqualTo(actual.getPosition()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmployeeAlphaUpdatableRelationshipsEquals(EmployeeAlpha expected, EmployeeAlpha actual) {
        assertThat(expected)
            .as("Verify EmployeeAlpha relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
