package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static xyz.jhmapstruct.domain.AssertUtils.bigDecimalCompareTo;

public class NextInvoiceMiMiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextInvoiceMiMiAllPropertiesEquals(NextInvoiceMiMi expected, NextInvoiceMiMi actual) {
        assertNextInvoiceMiMiAutoGeneratedPropertiesEquals(expected, actual);
        assertNextInvoiceMiMiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextInvoiceMiMiAllUpdatablePropertiesEquals(NextInvoiceMiMi expected, NextInvoiceMiMi actual) {
        assertNextInvoiceMiMiUpdatableFieldsEquals(expected, actual);
        assertNextInvoiceMiMiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextInvoiceMiMiAutoGeneratedPropertiesEquals(NextInvoiceMiMi expected, NextInvoiceMiMi actual) {
        assertThat(expected)
            .as("Verify NextInvoiceMiMi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextInvoiceMiMiUpdatableFieldsEquals(NextInvoiceMiMi expected, NextInvoiceMiMi actual) {
        assertThat(expected)
            .as("Verify NextInvoiceMiMi relevant properties")
            .satisfies(e -> assertThat(e.getInvoiceNumber()).as("check invoiceNumber").isEqualTo(actual.getInvoiceNumber()))
            .satisfies(e -> assertThat(e.getIssueDate()).as("check issueDate").isEqualTo(actual.getIssueDate()))
            .satisfies(e -> assertThat(e.getDueDate()).as("check dueDate").isEqualTo(actual.getDueDate()))
            .satisfies(e -> assertThat(e.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getAmount())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextInvoiceMiMiUpdatableRelationshipsEquals(NextInvoiceMiMi expected, NextInvoiceMiMi actual) {
        assertThat(expected)
            .as("Verify NextInvoiceMiMi relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
