package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static xyz.jhmapstruct.domain.AssertUtils.bigDecimalCompareTo;

public class NextProductMiMiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextProductMiMiAllPropertiesEquals(NextProductMiMi expected, NextProductMiMi actual) {
        assertNextProductMiMiAutoGeneratedPropertiesEquals(expected, actual);
        assertNextProductMiMiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextProductMiMiAllUpdatablePropertiesEquals(NextProductMiMi expected, NextProductMiMi actual) {
        assertNextProductMiMiUpdatableFieldsEquals(expected, actual);
        assertNextProductMiMiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextProductMiMiAutoGeneratedPropertiesEquals(NextProductMiMi expected, NextProductMiMi actual) {
        assertThat(expected)
            .as("Verify NextProductMiMi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextProductMiMiUpdatableFieldsEquals(NextProductMiMi expected, NextProductMiMi actual) {
        assertThat(expected)
            .as("Verify NextProductMiMi relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getPrice()))
            .satisfies(e -> assertThat(e.getStock()).as("check stock").isEqualTo(actual.getStock()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextProductMiMiUpdatableRelationshipsEquals(NextProductMiMi expected, NextProductMiMi actual) {
        assertThat(expected)
            .as("Verify NextProductMiMi relationships")
            .satisfies(e -> assertThat(e.getCategory()).as("check category").isEqualTo(actual.getCategory()))
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()))
            .satisfies(e -> assertThat(e.getOrder()).as("check order").isEqualTo(actual.getOrder()))
            .satisfies(e -> assertThat(e.getSuppliers()).as("check suppliers").isEqualTo(actual.getSuppliers()));
    }
}
