package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NextCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCategoryAllPropertiesEquals(NextCategory expected, NextCategory actual) {
        assertNextCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertNextCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCategoryAllUpdatablePropertiesEquals(NextCategory expected, NextCategory actual) {
        assertNextCategoryUpdatableFieldsEquals(expected, actual);
        assertNextCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCategoryAutoGeneratedPropertiesEquals(NextCategory expected, NextCategory actual) {
        assertThat(expected)
            .as("Verify NextCategory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCategoryUpdatableFieldsEquals(NextCategory expected, NextCategory actual) {
        assertThat(expected)
            .as("Verify NextCategory relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCategoryUpdatableRelationshipsEquals(NextCategory expected, NextCategory actual) {
        assertThat(expected)
            .as("Verify NextCategory relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
