package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static xyz.jhmapstruct.domain.AssertUtils.bigDecimalCompareTo;

public class NextInvoiceThetaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextInvoiceThetaAllPropertiesEquals(NextInvoiceTheta expected, NextInvoiceTheta actual) {
        assertNextInvoiceThetaAutoGeneratedPropertiesEquals(expected, actual);
        assertNextInvoiceThetaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextInvoiceThetaAllUpdatablePropertiesEquals(NextInvoiceTheta expected, NextInvoiceTheta actual) {
        assertNextInvoiceThetaUpdatableFieldsEquals(expected, actual);
        assertNextInvoiceThetaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextInvoiceThetaAutoGeneratedPropertiesEquals(NextInvoiceTheta expected, NextInvoiceTheta actual) {
        assertThat(expected)
            .as("Verify NextInvoiceTheta auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextInvoiceThetaUpdatableFieldsEquals(NextInvoiceTheta expected, NextInvoiceTheta actual) {
        assertThat(expected)
            .as("Verify NextInvoiceTheta relevant properties")
            .satisfies(e -> assertThat(e.getInvoiceNumber()).as("check invoiceNumber").isEqualTo(actual.getInvoiceNumber()))
            .satisfies(e -> assertThat(e.getIssueDate()).as("check issueDate").isEqualTo(actual.getIssueDate()))
            .satisfies(e -> assertThat(e.getDueDate()).as("check dueDate").isEqualTo(actual.getDueDate()))
            .satisfies(e -> assertThat(e.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getAmount())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextInvoiceThetaUpdatableRelationshipsEquals(NextInvoiceTheta expected, NextInvoiceTheta actual) {
        assertThat(expected)
            .as("Verify NextInvoiceTheta relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
