package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NextCategoryViViAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCategoryViViAllPropertiesEquals(NextCategoryViVi expected, NextCategoryViVi actual) {
        assertNextCategoryViViAutoGeneratedPropertiesEquals(expected, actual);
        assertNextCategoryViViAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCategoryViViAllUpdatablePropertiesEquals(NextCategoryViVi expected, NextCategoryViVi actual) {
        assertNextCategoryViViUpdatableFieldsEquals(expected, actual);
        assertNextCategoryViViUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCategoryViViAutoGeneratedPropertiesEquals(NextCategoryViVi expected, NextCategoryViVi actual) {
        assertThat(expected)
            .as("Verify NextCategoryViVi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCategoryViViUpdatableFieldsEquals(NextCategoryViVi expected, NextCategoryViVi actual) {
        assertThat(expected)
            .as("Verify NextCategoryViVi relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCategoryViViUpdatableRelationshipsEquals(NextCategoryViVi expected, NextCategoryViVi actual) {
        assertThat(expected)
            .as("Verify NextCategoryViVi relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
