package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NextEmployeeBetaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextEmployeeBetaAllPropertiesEquals(NextEmployeeBeta expected, NextEmployeeBeta actual) {
        assertNextEmployeeBetaAutoGeneratedPropertiesEquals(expected, actual);
        assertNextEmployeeBetaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextEmployeeBetaAllUpdatablePropertiesEquals(NextEmployeeBeta expected, NextEmployeeBeta actual) {
        assertNextEmployeeBetaUpdatableFieldsEquals(expected, actual);
        assertNextEmployeeBetaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextEmployeeBetaAutoGeneratedPropertiesEquals(NextEmployeeBeta expected, NextEmployeeBeta actual) {
        assertThat(expected)
            .as("Verify NextEmployeeBeta auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextEmployeeBetaUpdatableFieldsEquals(NextEmployeeBeta expected, NextEmployeeBeta actual) {
        assertThat(expected)
            .as("Verify NextEmployeeBeta relevant properties")
            .satisfies(e -> assertThat(e.getFirstName()).as("check firstName").isEqualTo(actual.getFirstName()))
            .satisfies(e -> assertThat(e.getLastName()).as("check lastName").isEqualTo(actual.getLastName()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getHireDate()).as("check hireDate").isEqualTo(actual.getHireDate()))
            .satisfies(e -> assertThat(e.getPosition()).as("check position").isEqualTo(actual.getPosition()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextEmployeeBetaUpdatableRelationshipsEquals(NextEmployeeBeta expected, NextEmployeeBeta actual) {
        assertThat(expected)
            .as("Verify NextEmployeeBeta relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
