package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NextCustomerThetaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCustomerThetaAllPropertiesEquals(NextCustomerTheta expected, NextCustomerTheta actual) {
        assertNextCustomerThetaAutoGeneratedPropertiesEquals(expected, actual);
        assertNextCustomerThetaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCustomerThetaAllUpdatablePropertiesEquals(NextCustomerTheta expected, NextCustomerTheta actual) {
        assertNextCustomerThetaUpdatableFieldsEquals(expected, actual);
        assertNextCustomerThetaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCustomerThetaAutoGeneratedPropertiesEquals(NextCustomerTheta expected, NextCustomerTheta actual) {
        assertThat(expected)
            .as("Verify NextCustomerTheta auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCustomerThetaUpdatableFieldsEquals(NextCustomerTheta expected, NextCustomerTheta actual) {
        assertThat(expected)
            .as("Verify NextCustomerTheta relevant properties")
            .satisfies(e -> assertThat(e.getFirstName()).as("check firstName").isEqualTo(actual.getFirstName()))
            .satisfies(e -> assertThat(e.getLastName()).as("check lastName").isEqualTo(actual.getLastName()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getPhoneNumber()).as("check phoneNumber").isEqualTo(actual.getPhoneNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCustomerThetaUpdatableRelationshipsEquals(NextCustomerTheta expected, NextCustomerTheta actual) {
        assertThat(expected)
            .as("Verify NextCustomerTheta relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
