package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NextReviewAlphaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextReviewAlphaAllPropertiesEquals(NextReviewAlpha expected, NextReviewAlpha actual) {
        assertNextReviewAlphaAutoGeneratedPropertiesEquals(expected, actual);
        assertNextReviewAlphaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextReviewAlphaAllUpdatablePropertiesEquals(NextReviewAlpha expected, NextReviewAlpha actual) {
        assertNextReviewAlphaUpdatableFieldsEquals(expected, actual);
        assertNextReviewAlphaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextReviewAlphaAutoGeneratedPropertiesEquals(NextReviewAlpha expected, NextReviewAlpha actual) {
        assertThat(expected)
            .as("Verify NextReviewAlpha auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextReviewAlphaUpdatableFieldsEquals(NextReviewAlpha expected, NextReviewAlpha actual) {
        assertThat(expected)
            .as("Verify NextReviewAlpha relevant properties")
            .satisfies(e -> assertThat(e.getRating()).as("check rating").isEqualTo(actual.getRating()))
            .satisfies(e -> assertThat(e.getComment()).as("check comment").isEqualTo(actual.getComment()))
            .satisfies(e -> assertThat(e.getReviewDate()).as("check reviewDate").isEqualTo(actual.getReviewDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextReviewAlphaUpdatableRelationshipsEquals(NextReviewAlpha expected, NextReviewAlpha actual) {
        assertThat(expected)
            .as("Verify NextReviewAlpha relationships")
            .satisfies(e -> assertThat(e.getProduct()).as("check product").isEqualTo(actual.getProduct()))
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
