package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NextCustomerMiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCustomerMiAllPropertiesEquals(NextCustomerMi expected, NextCustomerMi actual) {
        assertNextCustomerMiAutoGeneratedPropertiesEquals(expected, actual);
        assertNextCustomerMiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCustomerMiAllUpdatablePropertiesEquals(NextCustomerMi expected, NextCustomerMi actual) {
        assertNextCustomerMiUpdatableFieldsEquals(expected, actual);
        assertNextCustomerMiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCustomerMiAutoGeneratedPropertiesEquals(NextCustomerMi expected, NextCustomerMi actual) {
        assertThat(expected)
            .as("Verify NextCustomerMi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCustomerMiUpdatableFieldsEquals(NextCustomerMi expected, NextCustomerMi actual) {
        assertThat(expected)
            .as("Verify NextCustomerMi relevant properties")
            .satisfies(e -> assertThat(e.getFirstName()).as("check firstName").isEqualTo(actual.getFirstName()))
            .satisfies(e -> assertThat(e.getLastName()).as("check lastName").isEqualTo(actual.getLastName()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getPhoneNumber()).as("check phoneNumber").isEqualTo(actual.getPhoneNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCustomerMiUpdatableRelationshipsEquals(NextCustomerMi expected, NextCustomerMi actual) {
        assertThat(expected)
            .as("Verify NextCustomerMi relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
