package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NextSupplierBetaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextSupplierBetaAllPropertiesEquals(NextSupplierBeta expected, NextSupplierBeta actual) {
        assertNextSupplierBetaAutoGeneratedPropertiesEquals(expected, actual);
        assertNextSupplierBetaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextSupplierBetaAllUpdatablePropertiesEquals(NextSupplierBeta expected, NextSupplierBeta actual) {
        assertNextSupplierBetaUpdatableFieldsEquals(expected, actual);
        assertNextSupplierBetaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextSupplierBetaAutoGeneratedPropertiesEquals(NextSupplierBeta expected, NextSupplierBeta actual) {
        assertThat(expected)
            .as("Verify NextSupplierBeta auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextSupplierBetaUpdatableFieldsEquals(NextSupplierBeta expected, NextSupplierBeta actual) {
        assertThat(expected)
            .as("Verify NextSupplierBeta relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getContactPerson()).as("check contactPerson").isEqualTo(actual.getContactPerson()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getPhoneNumber()).as("check phoneNumber").isEqualTo(actual.getPhoneNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextSupplierBetaUpdatableRelationshipsEquals(NextSupplierBeta expected, NextSupplierBeta actual) {
        assertThat(expected)
            .as("Verify NextSupplierBeta relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()))
            .satisfies(e -> assertThat(e.getProducts()).as("check products").isEqualTo(actual.getProducts()));
    }
}
