package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShipmentThetaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentThetaAllPropertiesEquals(ShipmentTheta expected, ShipmentTheta actual) {
        assertShipmentThetaAutoGeneratedPropertiesEquals(expected, actual);
        assertShipmentThetaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentThetaAllUpdatablePropertiesEquals(ShipmentTheta expected, ShipmentTheta actual) {
        assertShipmentThetaUpdatableFieldsEquals(expected, actual);
        assertShipmentThetaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentThetaAutoGeneratedPropertiesEquals(ShipmentTheta expected, ShipmentTheta actual) {
        assertThat(expected)
            .as("Verify ShipmentTheta auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentThetaUpdatableFieldsEquals(ShipmentTheta expected, ShipmentTheta actual) {
        assertThat(expected)
            .as("Verify ShipmentTheta relevant properties")
            .satisfies(e -> assertThat(e.getTrackingNumber()).as("check trackingNumber").isEqualTo(actual.getTrackingNumber()))
            .satisfies(e -> assertThat(e.getShippedDate()).as("check shippedDate").isEqualTo(actual.getShippedDate()))
            .satisfies(e -> assertThat(e.getDeliveryDate()).as("check deliveryDate").isEqualTo(actual.getDeliveryDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentThetaUpdatableRelationshipsEquals(ShipmentTheta expected, ShipmentTheta actual) {
        assertThat(expected)
            .as("Verify ShipmentTheta relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
