package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CategoryViAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoryViAllPropertiesEquals(CategoryVi expected, CategoryVi actual) {
        assertCategoryViAutoGeneratedPropertiesEquals(expected, actual);
        assertCategoryViAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoryViAllUpdatablePropertiesEquals(CategoryVi expected, CategoryVi actual) {
        assertCategoryViUpdatableFieldsEquals(expected, actual);
        assertCategoryViUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoryViAutoGeneratedPropertiesEquals(CategoryVi expected, CategoryVi actual) {
        assertThat(expected)
            .as("Verify CategoryVi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoryViUpdatableFieldsEquals(CategoryVi expected, CategoryVi actual) {
        assertThat(expected)
            .as("Verify CategoryVi relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoryViUpdatableRelationshipsEquals(CategoryVi expected, CategoryVi actual) {
        // empty method
    }
}
