package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CustomerMiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerMiAllPropertiesEquals(CustomerMi expected, CustomerMi actual) {
        assertCustomerMiAutoGeneratedPropertiesEquals(expected, actual);
        assertCustomerMiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerMiAllUpdatablePropertiesEquals(CustomerMi expected, CustomerMi actual) {
        assertCustomerMiUpdatableFieldsEquals(expected, actual);
        assertCustomerMiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerMiAutoGeneratedPropertiesEquals(CustomerMi expected, CustomerMi actual) {
        assertThat(expected)
            .as("Verify CustomerMi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerMiUpdatableFieldsEquals(CustomerMi expected, CustomerMi actual) {
        assertThat(expected)
            .as("Verify CustomerMi relevant properties")
            .satisfies(e -> assertThat(e.getFirstName()).as("check firstName").isEqualTo(actual.getFirstName()))
            .satisfies(e -> assertThat(e.getLastName()).as("check lastName").isEqualTo(actual.getLastName()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getPhoneNumber()).as("check phoneNumber").isEqualTo(actual.getPhoneNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerMiUpdatableRelationshipsEquals(CustomerMi expected, CustomerMi actual) {
        // empty method
    }
}
