package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static xyz.jhmapstruct.domain.AssertUtils.bigDecimalCompareTo;

public class InvoiceViViAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceViViAllPropertiesEquals(InvoiceViVi expected, InvoiceViVi actual) {
        assertInvoiceViViAutoGeneratedPropertiesEquals(expected, actual);
        assertInvoiceViViAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceViViAllUpdatablePropertiesEquals(InvoiceViVi expected, InvoiceViVi actual) {
        assertInvoiceViViUpdatableFieldsEquals(expected, actual);
        assertInvoiceViViUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceViViAutoGeneratedPropertiesEquals(InvoiceViVi expected, InvoiceViVi actual) {
        assertThat(expected)
            .as("Verify InvoiceViVi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceViViUpdatableFieldsEquals(InvoiceViVi expected, InvoiceViVi actual) {
        assertThat(expected)
            .as("Verify InvoiceViVi relevant properties")
            .satisfies(e -> assertThat(e.getInvoiceNumber()).as("check invoiceNumber").isEqualTo(actual.getInvoiceNumber()))
            .satisfies(e -> assertThat(e.getIssueDate()).as("check issueDate").isEqualTo(actual.getIssueDate()))
            .satisfies(e -> assertThat(e.getDueDate()).as("check dueDate").isEqualTo(actual.getDueDate()))
            .satisfies(e -> assertThat(e.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getAmount())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceViViUpdatableRelationshipsEquals(InvoiceViVi expected, InvoiceViVi actual) {
        // empty method
    }
}
