package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static xyz.jhmapstruct.domain.AssertUtils.bigDecimalCompareTo;

public class PaymentViViAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentViViAllPropertiesEquals(PaymentViVi expected, PaymentViVi actual) {
        assertPaymentViViAutoGeneratedPropertiesEquals(expected, actual);
        assertPaymentViViAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentViViAllUpdatablePropertiesEquals(PaymentViVi expected, PaymentViVi actual) {
        assertPaymentViViUpdatableFieldsEquals(expected, actual);
        assertPaymentViViUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentViViAutoGeneratedPropertiesEquals(PaymentViVi expected, PaymentViVi actual) {
        assertThat(expected)
            .as("Verify PaymentViVi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentViViUpdatableFieldsEquals(PaymentViVi expected, PaymentViVi actual) {
        assertThat(expected)
            .as("Verify PaymentViVi relevant properties")
            .satisfies(e -> assertThat(e.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getAmount()))
            .satisfies(e -> assertThat(e.getPaymentDate()).as("check paymentDate").isEqualTo(actual.getPaymentDate()))
            .satisfies(e -> assertThat(e.getPaymentMethod()).as("check paymentMethod").isEqualTo(actual.getPaymentMethod()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentViViUpdatableRelationshipsEquals(PaymentViVi expected, PaymentViVi actual) {
        // empty method
    }
}
