package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReviewMiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewMiAllPropertiesEquals(ReviewMi expected, ReviewMi actual) {
        assertReviewMiAutoGeneratedPropertiesEquals(expected, actual);
        assertReviewMiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewMiAllUpdatablePropertiesEquals(ReviewMi expected, ReviewMi actual) {
        assertReviewMiUpdatableFieldsEquals(expected, actual);
        assertReviewMiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewMiAutoGeneratedPropertiesEquals(ReviewMi expected, ReviewMi actual) {
        assertThat(expected)
            .as("Verify ReviewMi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewMiUpdatableFieldsEquals(ReviewMi expected, ReviewMi actual) {
        assertThat(expected)
            .as("Verify ReviewMi relevant properties")
            .satisfies(e -> assertThat(e.getRating()).as("check rating").isEqualTo(actual.getRating()))
            .satisfies(e -> assertThat(e.getComment()).as("check comment").isEqualTo(actual.getComment()))
            .satisfies(e -> assertThat(e.getReviewDate()).as("check reviewDate").isEqualTo(actual.getReviewDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewMiUpdatableRelationshipsEquals(ReviewMi expected, ReviewMi actual) {
        assertThat(expected)
            .as("Verify ReviewMi relationships")
            .satisfies(e -> assertThat(e.getProduct()).as("check product").isEqualTo(actual.getProduct()));
    }
}
