package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CategorySigmaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategorySigmaAllPropertiesEquals(CategorySigma expected, CategorySigma actual) {
        assertCategorySigmaAutoGeneratedPropertiesEquals(expected, actual);
        assertCategorySigmaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategorySigmaAllUpdatablePropertiesEquals(CategorySigma expected, CategorySigma actual) {
        assertCategorySigmaUpdatableFieldsEquals(expected, actual);
        assertCategorySigmaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategorySigmaAutoGeneratedPropertiesEquals(CategorySigma expected, CategorySigma actual) {
        assertThat(expected)
            .as("Verify CategorySigma auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategorySigmaUpdatableFieldsEquals(CategorySigma expected, CategorySigma actual) {
        assertThat(expected)
            .as("Verify CategorySigma relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategorySigmaUpdatableRelationshipsEquals(CategorySigma expected, CategorySigma actual) {
        assertThat(expected)
            .as("Verify CategorySigma relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
