package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CustomerSigmaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerSigmaAllPropertiesEquals(CustomerSigma expected, CustomerSigma actual) {
        assertCustomerSigmaAutoGeneratedPropertiesEquals(expected, actual);
        assertCustomerSigmaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerSigmaAllUpdatablePropertiesEquals(CustomerSigma expected, CustomerSigma actual) {
        assertCustomerSigmaUpdatableFieldsEquals(expected, actual);
        assertCustomerSigmaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerSigmaAutoGeneratedPropertiesEquals(CustomerSigma expected, CustomerSigma actual) {
        assertThat(expected)
            .as("Verify CustomerSigma auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerSigmaUpdatableFieldsEquals(CustomerSigma expected, CustomerSigma actual) {
        assertThat(expected)
            .as("Verify CustomerSigma relevant properties")
            .satisfies(e -> assertThat(e.getFirstName()).as("check firstName").isEqualTo(actual.getFirstName()))
            .satisfies(e -> assertThat(e.getLastName()).as("check lastName").isEqualTo(actual.getLastName()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getPhoneNumber()).as("check phoneNumber").isEqualTo(actual.getPhoneNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerSigmaUpdatableRelationshipsEquals(CustomerSigma expected, CustomerSigma actual) {
        assertThat(expected)
            .as("Verify CustomerSigma relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
