package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NextShipmentGammaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextShipmentGammaAllPropertiesEquals(NextShipmentGamma expected, NextShipmentGamma actual) {
        assertNextShipmentGammaAutoGeneratedPropertiesEquals(expected, actual);
        assertNextShipmentGammaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextShipmentGammaAllUpdatablePropertiesEquals(NextShipmentGamma expected, NextShipmentGamma actual) {
        assertNextShipmentGammaUpdatableFieldsEquals(expected, actual);
        assertNextShipmentGammaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextShipmentGammaAutoGeneratedPropertiesEquals(NextShipmentGamma expected, NextShipmentGamma actual) {
        assertThat(expected)
            .as("Verify NextShipmentGamma auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextShipmentGammaUpdatableFieldsEquals(NextShipmentGamma expected, NextShipmentGamma actual) {
        assertThat(expected)
            .as("Verify NextShipmentGamma relevant properties")
            .satisfies(e -> assertThat(e.getTrackingNumber()).as("check trackingNumber").isEqualTo(actual.getTrackingNumber()))
            .satisfies(e -> assertThat(e.getShippedDate()).as("check shippedDate").isEqualTo(actual.getShippedDate()))
            .satisfies(e -> assertThat(e.getDeliveryDate()).as("check deliveryDate").isEqualTo(actual.getDeliveryDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextShipmentGammaUpdatableRelationshipsEquals(NextShipmentGamma expected, NextShipmentGamma actual) {
        assertThat(expected)
            .as("Verify NextShipmentGamma relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
