package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NextReviewGammaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextReviewGammaAllPropertiesEquals(NextReviewGamma expected, NextReviewGamma actual) {
        assertNextReviewGammaAutoGeneratedPropertiesEquals(expected, actual);
        assertNextReviewGammaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextReviewGammaAllUpdatablePropertiesEquals(NextReviewGamma expected, NextReviewGamma actual) {
        assertNextReviewGammaUpdatableFieldsEquals(expected, actual);
        assertNextReviewGammaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextReviewGammaAutoGeneratedPropertiesEquals(NextReviewGamma expected, NextReviewGamma actual) {
        assertThat(expected)
            .as("Verify NextReviewGamma auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextReviewGammaUpdatableFieldsEquals(NextReviewGamma expected, NextReviewGamma actual) {
        assertThat(expected)
            .as("Verify NextReviewGamma relevant properties")
            .satisfies(e -> assertThat(e.getRating()).as("check rating").isEqualTo(actual.getRating()))
            .satisfies(e -> assertThat(e.getComment()).as("check comment").isEqualTo(actual.getComment()))
            .satisfies(e -> assertThat(e.getReviewDate()).as("check reviewDate").isEqualTo(actual.getReviewDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextReviewGammaUpdatableRelationshipsEquals(NextReviewGamma expected, NextReviewGamma actual) {
        assertThat(expected)
            .as("Verify NextReviewGamma relationships")
            .satisfies(e -> assertThat(e.getProduct()).as("check product").isEqualTo(actual.getProduct()))
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
