package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NextShipmentMiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextShipmentMiAllPropertiesEquals(NextShipmentMi expected, NextShipmentMi actual) {
        assertNextShipmentMiAutoGeneratedPropertiesEquals(expected, actual);
        assertNextShipmentMiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextShipmentMiAllUpdatablePropertiesEquals(NextShipmentMi expected, NextShipmentMi actual) {
        assertNextShipmentMiUpdatableFieldsEquals(expected, actual);
        assertNextShipmentMiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextShipmentMiAutoGeneratedPropertiesEquals(NextShipmentMi expected, NextShipmentMi actual) {
        assertThat(expected)
            .as("Verify NextShipmentMi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextShipmentMiUpdatableFieldsEquals(NextShipmentMi expected, NextShipmentMi actual) {
        assertThat(expected)
            .as("Verify NextShipmentMi relevant properties")
            .satisfies(e -> assertThat(e.getTrackingNumber()).as("check trackingNumber").isEqualTo(actual.getTrackingNumber()))
            .satisfies(e -> assertThat(e.getShippedDate()).as("check shippedDate").isEqualTo(actual.getShippedDate()))
            .satisfies(e -> assertThat(e.getDeliveryDate()).as("check deliveryDate").isEqualTo(actual.getDeliveryDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextShipmentMiUpdatableRelationshipsEquals(NextShipmentMi expected, NextShipmentMi actual) {
        assertThat(expected)
            .as("Verify NextShipmentMi relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
