package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static xyz.jhmapstruct.domain.AssertUtils.bigDecimalCompareTo;

public class NextInvoiceSigmaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextInvoiceSigmaAllPropertiesEquals(NextInvoiceSigma expected, NextInvoiceSigma actual) {
        assertNextInvoiceSigmaAutoGeneratedPropertiesEquals(expected, actual);
        assertNextInvoiceSigmaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextInvoiceSigmaAllUpdatablePropertiesEquals(NextInvoiceSigma expected, NextInvoiceSigma actual) {
        assertNextInvoiceSigmaUpdatableFieldsEquals(expected, actual);
        assertNextInvoiceSigmaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextInvoiceSigmaAutoGeneratedPropertiesEquals(NextInvoiceSigma expected, NextInvoiceSigma actual) {
        assertThat(expected)
            .as("Verify NextInvoiceSigma auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextInvoiceSigmaUpdatableFieldsEquals(NextInvoiceSigma expected, NextInvoiceSigma actual) {
        assertThat(expected)
            .as("Verify NextInvoiceSigma relevant properties")
            .satisfies(e -> assertThat(e.getInvoiceNumber()).as("check invoiceNumber").isEqualTo(actual.getInvoiceNumber()))
            .satisfies(e -> assertThat(e.getIssueDate()).as("check issueDate").isEqualTo(actual.getIssueDate()))
            .satisfies(e -> assertThat(e.getDueDate()).as("check dueDate").isEqualTo(actual.getDueDate()))
            .satisfies(e -> assertThat(e.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getAmount())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextInvoiceSigmaUpdatableRelationshipsEquals(NextInvoiceSigma expected, NextInvoiceSigma actual) {
        assertThat(expected)
            .as("Verify NextInvoiceSigma relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
