package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static xyz.jhmapstruct.domain.AssertUtils.bigDecimalCompareTo;

public class NextPaymentGammaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextPaymentGammaAllPropertiesEquals(NextPaymentGamma expected, NextPaymentGamma actual) {
        assertNextPaymentGammaAutoGeneratedPropertiesEquals(expected, actual);
        assertNextPaymentGammaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextPaymentGammaAllUpdatablePropertiesEquals(NextPaymentGamma expected, NextPaymentGamma actual) {
        assertNextPaymentGammaUpdatableFieldsEquals(expected, actual);
        assertNextPaymentGammaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextPaymentGammaAutoGeneratedPropertiesEquals(NextPaymentGamma expected, NextPaymentGamma actual) {
        assertThat(expected)
            .as("Verify NextPaymentGamma auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextPaymentGammaUpdatableFieldsEquals(NextPaymentGamma expected, NextPaymentGamma actual) {
        assertThat(expected)
            .as("Verify NextPaymentGamma relevant properties")
            .satisfies(e -> assertThat(e.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getAmount()))
            .satisfies(e -> assertThat(e.getPaymentDate()).as("check paymentDate").isEqualTo(actual.getPaymentDate()))
            .satisfies(e -> assertThat(e.getPaymentMethod()).as("check paymentMethod").isEqualTo(actual.getPaymentMethod()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextPaymentGammaUpdatableRelationshipsEquals(NextPaymentGamma expected, NextPaymentGamma actual) {
        assertThat(expected)
            .as("Verify NextPaymentGamma relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
