package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NextCustomerBetaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCustomerBetaAllPropertiesEquals(NextCustomerBeta expected, NextCustomerBeta actual) {
        assertNextCustomerBetaAutoGeneratedPropertiesEquals(expected, actual);
        assertNextCustomerBetaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCustomerBetaAllUpdatablePropertiesEquals(NextCustomerBeta expected, NextCustomerBeta actual) {
        assertNextCustomerBetaUpdatableFieldsEquals(expected, actual);
        assertNextCustomerBetaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCustomerBetaAutoGeneratedPropertiesEquals(NextCustomerBeta expected, NextCustomerBeta actual) {
        assertThat(expected)
            .as("Verify NextCustomerBeta auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCustomerBetaUpdatableFieldsEquals(NextCustomerBeta expected, NextCustomerBeta actual) {
        assertThat(expected)
            .as("Verify NextCustomerBeta relevant properties")
            .satisfies(e -> assertThat(e.getFirstName()).as("check firstName").isEqualTo(actual.getFirstName()))
            .satisfies(e -> assertThat(e.getLastName()).as("check lastName").isEqualTo(actual.getLastName()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getPhoneNumber()).as("check phoneNumber").isEqualTo(actual.getPhoneNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCustomerBetaUpdatableRelationshipsEquals(NextCustomerBeta expected, NextCustomerBeta actual) {
        assertThat(expected)
            .as("Verify NextCustomerBeta relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
