package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NextCategorySigmaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCategorySigmaAllPropertiesEquals(NextCategorySigma expected, NextCategorySigma actual) {
        assertNextCategorySigmaAutoGeneratedPropertiesEquals(expected, actual);
        assertNextCategorySigmaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCategorySigmaAllUpdatablePropertiesEquals(NextCategorySigma expected, NextCategorySigma actual) {
        assertNextCategorySigmaUpdatableFieldsEquals(expected, actual);
        assertNextCategorySigmaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCategorySigmaAutoGeneratedPropertiesEquals(NextCategorySigma expected, NextCategorySigma actual) {
        assertThat(expected)
            .as("Verify NextCategorySigma auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCategorySigmaUpdatableFieldsEquals(NextCategorySigma expected, NextCategorySigma actual) {
        assertThat(expected)
            .as("Verify NextCategorySigma relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNextCategorySigmaUpdatableRelationshipsEquals(NextCategorySigma expected, NextCategorySigma actual) {
        assertThat(expected)
            .as("Verify NextCategorySigma relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
