package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReviewGammaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewGammaAllPropertiesEquals(ReviewGamma expected, ReviewGamma actual) {
        assertReviewGammaAutoGeneratedPropertiesEquals(expected, actual);
        assertReviewGammaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewGammaAllUpdatablePropertiesEquals(ReviewGamma expected, ReviewGamma actual) {
        assertReviewGammaUpdatableFieldsEquals(expected, actual);
        assertReviewGammaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewGammaAutoGeneratedPropertiesEquals(ReviewGamma expected, ReviewGamma actual) {
        assertThat(expected)
            .as("Verify ReviewGamma auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewGammaUpdatableFieldsEquals(ReviewGamma expected, ReviewGamma actual) {
        assertThat(expected)
            .as("Verify ReviewGamma relevant properties")
            .satisfies(e -> assertThat(e.getRating()).as("check rating").isEqualTo(actual.getRating()))
            .satisfies(e -> assertThat(e.getComment()).as("check comment").isEqualTo(actual.getComment()))
            .satisfies(e -> assertThat(e.getReviewDate()).as("check reviewDate").isEqualTo(actual.getReviewDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewGammaUpdatableRelationshipsEquals(ReviewGamma expected, ReviewGamma actual) {
        assertThat(expected)
            .as("Verify ReviewGamma relationships")
            .satisfies(e -> assertThat(e.getProduct()).as("check product").isEqualTo(actual.getProduct()))
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
