package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShipmentAlphaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentAlphaAllPropertiesEquals(ShipmentAlpha expected, ShipmentAlpha actual) {
        assertShipmentAlphaAutoGeneratedPropertiesEquals(expected, actual);
        assertShipmentAlphaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentAlphaAllUpdatablePropertiesEquals(ShipmentAlpha expected, ShipmentAlpha actual) {
        assertShipmentAlphaUpdatableFieldsEquals(expected, actual);
        assertShipmentAlphaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentAlphaAutoGeneratedPropertiesEquals(ShipmentAlpha expected, ShipmentAlpha actual) {
        assertThat(expected)
            .as("Verify ShipmentAlpha auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentAlphaUpdatableFieldsEquals(ShipmentAlpha expected, ShipmentAlpha actual) {
        assertThat(expected)
            .as("Verify ShipmentAlpha relevant properties")
            .satisfies(e -> assertThat(e.getTrackingNumber()).as("check trackingNumber").isEqualTo(actual.getTrackingNumber()))
            .satisfies(e -> assertThat(e.getShippedDate()).as("check shippedDate").isEqualTo(actual.getShippedDate()))
            .satisfies(e -> assertThat(e.getDeliveryDate()).as("check deliveryDate").isEqualTo(actual.getDeliveryDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentAlphaUpdatableRelationshipsEquals(ShipmentAlpha expected, ShipmentAlpha actual) {
        assertThat(expected)
            .as("Verify ShipmentAlpha relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
