package ai.realworld.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlBestToothViAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlBestToothViAllPropertiesEquals(AlBestToothVi expected, AlBestToothVi actual) {
        assertAlBestToothViAutoGeneratedPropertiesEquals(expected, actual);
        assertAlBestToothViAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlBestToothViAllUpdatablePropertiesEquals(AlBestToothVi expected, AlBestToothVi actual) {
        assertAlBestToothViUpdatableFieldsEquals(expected, actual);
        assertAlBestToothViUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlBestToothViAutoGeneratedPropertiesEquals(AlBestToothVi expected, AlBestToothVi actual) {
        assertThat(expected)
            .as("Verify AlBestToothVi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlBestToothViUpdatableFieldsEquals(AlBestToothVi expected, AlBestToothVi actual) {
        assertThat(expected)
            .as("Verify AlBestToothVi relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlBestToothViUpdatableRelationshipsEquals(AlBestToothVi expected, AlBestToothVi actual) {
        // empty method
    }
}
