package ai.realworld.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlPacinoVoucherAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlPacinoVoucherAllPropertiesEquals(AlPacinoVoucher expected, AlPacinoVoucher actual) {
        assertAlPacinoVoucherAutoGeneratedPropertiesEquals(expected, actual);
        assertAlPacinoVoucherAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlPacinoVoucherAllUpdatablePropertiesEquals(AlPacinoVoucher expected, AlPacinoVoucher actual) {
        assertAlPacinoVoucherUpdatableFieldsEquals(expected, actual);
        assertAlPacinoVoucherUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlPacinoVoucherAutoGeneratedPropertiesEquals(AlPacinoVoucher expected, AlPacinoVoucher actual) {
        assertThat(expected)
            .as("Verify AlPacinoVoucher auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlPacinoVoucherUpdatableFieldsEquals(AlPacinoVoucher expected, AlPacinoVoucher actual) {
        assertThat(expected)
            .as("Verify AlPacinoVoucher relevant properties")
            .satisfies(e -> assertThat(e.getSourceTitle()).as("check sourceTitle").isEqualTo(actual.getSourceTitle()))
            .satisfies(e -> assertThat(e.getSourceUrl()).as("check sourceUrl").isEqualTo(actual.getSourceUrl()))
            .satisfies(e -> assertThat(e.getCollectedDate()).as("check collectedDate").isEqualTo(actual.getCollectedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlPacinoVoucherUpdatableRelationshipsEquals(AlPacinoVoucher expected, AlPacinoVoucher actual) {
        assertThat(expected)
            .as("Verify AlPacinoVoucher relationships")
            .satisfies(e -> assertThat(e.getUser()).as("check user").isEqualTo(actual.getUser()))
            .satisfies(e -> assertThat(e.getVoucher()).as("check voucher").isEqualTo(actual.getVoucher()))
            .satisfies(e -> assertThat(e.getApplication()).as("check application").isEqualTo(actual.getApplication()));
    }
}
