package ai.realworld.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlPounderViAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlPounderViAllPropertiesEquals(AlPounderVi expected, AlPounderVi actual) {
        assertAlPounderViAutoGeneratedPropertiesEquals(expected, actual);
        assertAlPounderViAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlPounderViAllUpdatablePropertiesEquals(AlPounderVi expected, AlPounderVi actual) {
        assertAlPounderViUpdatableFieldsEquals(expected, actual);
        assertAlPounderViUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlPounderViAutoGeneratedPropertiesEquals(AlPounderVi expected, AlPounderVi actual) {
        assertThat(expected)
            .as("Verify AlPounderVi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlPounderViUpdatableFieldsEquals(AlPounderVi expected, AlPounderVi actual) {
        assertThat(expected)
            .as("Verify AlPounderVi relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getWeight()).as("check weight").isEqualTo(actual.getWeight()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlPounderViUpdatableRelationshipsEquals(AlPounderVi expected, AlPounderVi actual) {
        assertThat(expected)
            .as("Verify AlPounderVi relationships")
            .satisfies(e -> assertThat(e.getAttributeTaxonomy()).as("check attributeTaxonomy").isEqualTo(actual.getAttributeTaxonomy()))
            .satisfies(e -> assertThat(e.getApplication()).as("check application").isEqualTo(actual.getApplication()));
    }
}
