package ai.realworld.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HashRossViAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHashRossViAllPropertiesEquals(HashRossVi expected, HashRossVi actual) {
        assertHashRossViAutoGeneratedPropertiesEquals(expected, actual);
        assertHashRossViAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHashRossViAllUpdatablePropertiesEquals(HashRossVi expected, HashRossVi actual) {
        assertHashRossViUpdatableFieldsEquals(expected, actual);
        assertHashRossViUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHashRossViAutoGeneratedPropertiesEquals(HashRossVi expected, HashRossVi actual) {
        assertThat(expected)
            .as("Verify HashRossVi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHashRossViUpdatableFieldsEquals(HashRossVi expected, HashRossVi actual) {
        assertThat(expected)
            .as("Verify HashRossVi relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getSlug()).as("check slug").isEqualTo(actual.getSlug()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e ->
                assertThat(e.getPermissionGridJason()).as("check permissionGridJason").isEqualTo(actual.getPermissionGridJason())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHashRossViUpdatableRelationshipsEquals(HashRossVi expected, HashRossVi actual) {
        // empty method
    }
}
