package ai.realworld.domain;

import static ai.realworld.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class AlGoreAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlGoreAllPropertiesEquals(AlGore expected, AlGore actual) {
        assertAlGoreAutoGeneratedPropertiesEquals(expected, actual);
        assertAlGoreAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlGoreAllUpdatablePropertiesEquals(AlGore expected, AlGore actual) {
        assertAlGoreUpdatableFieldsEquals(expected, actual);
        assertAlGoreUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlGoreAutoGeneratedPropertiesEquals(AlGore expected, AlGore actual) {
        assertThat(expected)
            .as("Verify AlGore auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlGoreUpdatableFieldsEquals(AlGore expected, AlGore actual) {
        assertThat(expected)
            .as("Verify AlGore relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDiscountType()).as("check discountType").isEqualTo(actual.getDiscountType()))
            .satisfies(e ->
                assertThat(e.getDiscountRate())
                    .as("check discountRate")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getDiscountRate())
            )
            .satisfies(e -> assertThat(e.getScope()).as("check scope").isEqualTo(actual.getScope()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlGoreUpdatableRelationshipsEquals(AlGore expected, AlGore actual) {
        assertThat(expected)
            .as("Verify AlGore relationships")
            .satisfies(e -> assertThat(e.getBizRelation()).as("check bizRelation").isEqualTo(actual.getBizRelation()))
            .satisfies(e -> assertThat(e.getApplication()).as("check application").isEqualTo(actual.getApplication()));
    }
}
