package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CustomerViAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerViAllPropertiesEquals(CustomerVi expected, CustomerVi actual) {
        assertCustomerViAutoGeneratedPropertiesEquals(expected, actual);
        assertCustomerViAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerViAllUpdatablePropertiesEquals(CustomerVi expected, CustomerVi actual) {
        assertCustomerViUpdatableFieldsEquals(expected, actual);
        assertCustomerViUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerViAutoGeneratedPropertiesEquals(CustomerVi expected, CustomerVi actual) {
        assertThat(expected)
            .as("Verify CustomerVi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerViUpdatableFieldsEquals(CustomerVi expected, CustomerVi actual) {
        assertThat(expected)
            .as("Verify CustomerVi relevant properties")
            .satisfies(e -> assertThat(e.getFirstName()).as("check firstName").isEqualTo(actual.getFirstName()))
            .satisfies(e -> assertThat(e.getLastName()).as("check lastName").isEqualTo(actual.getLastName()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getPhoneNumber()).as("check phoneNumber").isEqualTo(actual.getPhoneNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerViUpdatableRelationshipsEquals(CustomerVi expected, CustomerVi actual) {
        assertThat(expected)
            .as("Verify CustomerVi relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
