package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReviewViAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewViAllPropertiesEquals(ReviewVi expected, ReviewVi actual) {
        assertReviewViAutoGeneratedPropertiesEquals(expected, actual);
        assertReviewViAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewViAllUpdatablePropertiesEquals(ReviewVi expected, ReviewVi actual) {
        assertReviewViUpdatableFieldsEquals(expected, actual);
        assertReviewViUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewViAutoGeneratedPropertiesEquals(ReviewVi expected, ReviewVi actual) {
        assertThat(expected)
            .as("Verify ReviewVi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewViUpdatableFieldsEquals(ReviewVi expected, ReviewVi actual) {
        assertThat(expected)
            .as("Verify ReviewVi relevant properties")
            .satisfies(e -> assertThat(e.getRating()).as("check rating").isEqualTo(actual.getRating()))
            .satisfies(e -> assertThat(e.getComment()).as("check comment").isEqualTo(actual.getComment()))
            .satisfies(e -> assertThat(e.getReviewDate()).as("check reviewDate").isEqualTo(actual.getReviewDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewViUpdatableRelationshipsEquals(ReviewVi expected, ReviewVi actual) {
        assertThat(expected)
            .as("Verify ReviewVi relationships")
            .satisfies(e -> assertThat(e.getProduct()).as("check product").isEqualTo(actual.getProduct()))
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
