package xyz.jhmapstruct.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static xyz.jhmapstruct.domain.AssertUtils.bigDecimalCompareTo;

public class PaymentMiMiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentMiMiAllPropertiesEquals(PaymentMiMi expected, PaymentMiMi actual) {
        assertPaymentMiMiAutoGeneratedPropertiesEquals(expected, actual);
        assertPaymentMiMiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentMiMiAllUpdatablePropertiesEquals(PaymentMiMi expected, PaymentMiMi actual) {
        assertPaymentMiMiUpdatableFieldsEquals(expected, actual);
        assertPaymentMiMiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentMiMiAutoGeneratedPropertiesEquals(PaymentMiMi expected, PaymentMiMi actual) {
        assertThat(expected)
            .as("Verify PaymentMiMi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentMiMiUpdatableFieldsEquals(PaymentMiMi expected, PaymentMiMi actual) {
        assertThat(expected)
            .as("Verify PaymentMiMi relevant properties")
            .satisfies(e -> assertThat(e.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getAmount()))
            .satisfies(e -> assertThat(e.getPaymentDate()).as("check paymentDate").isEqualTo(actual.getPaymentDate()))
            .satisfies(e -> assertThat(e.getPaymentMethod()).as("check paymentMethod").isEqualTo(actual.getPaymentMethod()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentMiMiUpdatableRelationshipsEquals(PaymentMiMi expected, PaymentMiMi actual) {
        assertThat(expected)
            .as("Verify PaymentMiMi relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
