package ai.realworld.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlGoogleMeetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlGoogleMeetAllPropertiesEquals(AlGoogleMeet expected, AlGoogleMeet actual) {
        assertAlGoogleMeetAutoGeneratedPropertiesEquals(expected, actual);
        assertAlGoogleMeetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlGoogleMeetAllUpdatablePropertiesEquals(AlGoogleMeet expected, AlGoogleMeet actual) {
        assertAlGoogleMeetUpdatableFieldsEquals(expected, actual);
        assertAlGoogleMeetUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlGoogleMeetAutoGeneratedPropertiesEquals(AlGoogleMeet expected, AlGoogleMeet actual) {
        assertThat(expected)
            .as("Verify AlGoogleMeet auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlGoogleMeetUpdatableFieldsEquals(AlGoogleMeet expected, AlGoogleMeet actual) {
        assertThat(expected)
            .as("Verify AlGoogleMeet relevant properties")
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e ->
                assertThat(e.getNumberOfParticipants()).as("check numberOfParticipants").isEqualTo(actual.getNumberOfParticipants())
            )
            .satisfies(e -> assertThat(e.getPlannedDate()).as("check plannedDate").isEqualTo(actual.getPlannedDate()))
            .satisfies(e ->
                assertThat(e.getPlannedDurationInMinutes())
                    .as("check plannedDurationInMinutes")
                    .isEqualTo(actual.getPlannedDurationInMinutes())
            )
            .satisfies(e -> assertThat(e.getActualDate()).as("check actualDate").isEqualTo(actual.getActualDate()))
            .satisfies(e ->
                assertThat(e.getActualDurationInMinutes())
                    .as("check actualDurationInMinutes")
                    .isEqualTo(actual.getActualDurationInMinutes())
            )
            .satisfies(e -> assertThat(e.getContentJason()).as("check contentJason").isEqualTo(actual.getContentJason()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlGoogleMeetUpdatableRelationshipsEquals(AlGoogleMeet expected, AlGoogleMeet actual) {
        assertThat(expected)
            .as("Verify AlGoogleMeet relationships")
            .satisfies(e -> assertThat(e.getCustomer()).as("check customer").isEqualTo(actual.getCustomer()))
            .satisfies(e -> assertThat(e.getAgency()).as("check agency").isEqualTo(actual.getAgency()))
            .satisfies(e -> assertThat(e.getPersonInCharge()).as("check personInCharge").isEqualTo(actual.getPersonInCharge()))
            .satisfies(e -> assertThat(e.getApplication()).as("check application").isEqualTo(actual.getApplication()));
    }
}
