package ai.realworld.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlLeandroPlayingTimeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlLeandroPlayingTimeAllPropertiesEquals(AlLeandroPlayingTime expected, AlLeandroPlayingTime actual) {
        assertAlLeandroPlayingTimeAutoGeneratedPropertiesEquals(expected, actual);
        assertAlLeandroPlayingTimeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlLeandroPlayingTimeAllUpdatablePropertiesEquals(AlLeandroPlayingTime expected, AlLeandroPlayingTime actual) {
        assertAlLeandroPlayingTimeUpdatableFieldsEquals(expected, actual);
        assertAlLeandroPlayingTimeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlLeandroPlayingTimeAutoGeneratedPropertiesEquals(AlLeandroPlayingTime expected, AlLeandroPlayingTime actual) {
        assertThat(expected)
            .as("Verify AlLeandroPlayingTime auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlLeandroPlayingTimeUpdatableFieldsEquals(AlLeandroPlayingTime expected, AlLeandroPlayingTime actual) {
        assertThat(expected)
            .as("Verify AlLeandroPlayingTime relevant properties")
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getWonDate()).as("check wonDate").isEqualTo(actual.getWonDate()))
            .satisfies(e ->
                assertThat(e.getSentAwardToPlayerAt()).as("check sentAwardToPlayerAt").isEqualTo(actual.getSentAwardToPlayerAt())
            )
            .satisfies(e ->
                assertThat(e.getSentAwardToPlayerBy()).as("check sentAwardToPlayerBy").isEqualTo(actual.getSentAwardToPlayerBy())
            )
            .satisfies(e ->
                assertThat(e.getPlayerReceivedTheAwardAt())
                    .as("check playerReceivedTheAwardAt")
                    .isEqualTo(actual.getPlayerReceivedTheAwardAt())
            )
            .satisfies(e -> assertThat(e.getPlaySourceTime()).as("check playSourceTime").isEqualTo(actual.getPlaySourceTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlLeandroPlayingTimeUpdatableRelationshipsEquals(AlLeandroPlayingTime expected, AlLeandroPlayingTime actual) {
        assertThat(expected)
            .as("Verify AlLeandroPlayingTime relationships")
            .satisfies(e -> assertThat(e.getMiniGame()).as("check miniGame").isEqualTo(actual.getMiniGame()))
            .satisfies(e -> assertThat(e.getUser()).as("check user").isEqualTo(actual.getUser()))
            .satisfies(e -> assertThat(e.getAward()).as("check award").isEqualTo(actual.getAward()))
            .satisfies(e -> assertThat(e.getApplication()).as("check application").isEqualTo(actual.getApplication()));
    }
}
