package ai.realworld.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AntonioBanderasAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAntonioBanderasAllPropertiesEquals(AntonioBanderas expected, AntonioBanderas actual) {
        assertAntonioBanderasAutoGeneratedPropertiesEquals(expected, actual);
        assertAntonioBanderasAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAntonioBanderasAllUpdatablePropertiesEquals(AntonioBanderas expected, AntonioBanderas actual) {
        assertAntonioBanderasUpdatableFieldsEquals(expected, actual);
        assertAntonioBanderasUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAntonioBanderasAutoGeneratedPropertiesEquals(AntonioBanderas expected, AntonioBanderas actual) {
        assertThat(expected)
            .as("Verify AntonioBanderas auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAntonioBanderasUpdatableFieldsEquals(AntonioBanderas expected, AntonioBanderas actual) {
        assertThat(expected)
            .as("Verify AntonioBanderas relevant properties")
            .satisfies(e -> assertThat(e.getLevel()).as("check level").isEqualTo(actual.getLevel()))
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getFullName()).as("check fullName").isEqualTo(actual.getFullName()))
            .satisfies(e -> assertThat(e.getNativeName()).as("check nativeName").isEqualTo(actual.getNativeName()))
            .satisfies(e -> assertThat(e.getOfficialCode()).as("check officialCode").isEqualTo(actual.getOfficialCode()))
            .satisfies(e -> assertThat(e.getDivisionTerm()).as("check divisionTerm").isEqualTo(actual.getDivisionTerm()))
            .satisfies(e -> assertThat(e.getIsDeleted()).as("check isDeleted").isEqualTo(actual.getIsDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAntonioBanderasUpdatableRelationshipsEquals(AntonioBanderas expected, AntonioBanderas actual) {
        assertThat(expected)
            .as("Verify AntonioBanderas relationships")
            .satisfies(e -> assertThat(e.getCurrent()).as("check current").isEqualTo(actual.getCurrent()))
            .satisfies(e -> assertThat(e.getParent()).as("check parent").isEqualTo(actual.getParent()));
    }
}
