package ai.realworld.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MagharettiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMagharettiAllPropertiesEquals(Magharetti expected, Magharetti actual) {
        assertMagharettiAutoGeneratedPropertiesEquals(expected, actual);
        assertMagharettiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMagharettiAllUpdatablePropertiesEquals(Magharetti expected, Magharetti actual) {
        assertMagharettiUpdatableFieldsEquals(expected, actual);
        assertMagharettiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMagharettiAutoGeneratedPropertiesEquals(Magharetti expected, Magharetti actual) {
        assertThat(expected)
            .as("Verify Magharetti auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMagharettiUpdatableFieldsEquals(Magharetti expected, Magharetti actual) {
        assertThat(expected)
            .as("Verify Magharetti relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getLabel()).as("check label").isEqualTo(actual.getLabel()))
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMagharettiUpdatableRelationshipsEquals(Magharetti expected, Magharetti actual) {
        // empty method
    }
}
