package ai.realworld.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PamelaLouisAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPamelaLouisAllPropertiesEquals(PamelaLouis expected, PamelaLouis actual) {
        assertPamelaLouisAutoGeneratedPropertiesEquals(expected, actual);
        assertPamelaLouisAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPamelaLouisAllUpdatablePropertiesEquals(PamelaLouis expected, PamelaLouis actual) {
        assertPamelaLouisUpdatableFieldsEquals(expected, actual);
        assertPamelaLouisUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPamelaLouisAutoGeneratedPropertiesEquals(PamelaLouis expected, PamelaLouis actual) {
        assertThat(expected)
            .as("Verify PamelaLouis auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPamelaLouisUpdatableFieldsEquals(PamelaLouis expected, PamelaLouis actual) {
        assertThat(expected)
            .as("Verify PamelaLouis relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getConfigJason()).as("check configJason").isEqualTo(actual.getConfigJason()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPamelaLouisUpdatableRelationshipsEquals(PamelaLouis expected, PamelaLouis actual) {
        // empty method
    }
}
